name: Generate Doxygen Documentation

on:
  push:
    branches:
      - main
      - development

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures history is checked out

      - name: Install Doxygen
        run: sudo apt-get install doxygen

      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # The output directory of your Doxygen documentation
